import { useEffect } from 'react';
import { ArrowUpRight, Database, LockKeyhole, ShieldCheck } from 'lucide-react';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';
import { SectionLabel } from '../components/SectionLabel';
import { Reveal } from '../components/Reveal';
import { NetworkVisual } from '../components/NetworkVisual';
import { CTA } from '../components/CTA';
import { DashboardShell } from '../components/DashboardShell';

function Product() { useEffect(() => { document.title = 'Lorvane — Research platform'; }, []); return <><Header /><section className="product-hero"><div className="container product-hero-grid"><div><SectionLabel>LORVANE RESEARCH PLATFORM</SectionLabel><h1>A research workspace built around <em>knowledge discovery.</em></h1><p>Collect, organize, search, retrieve, review, and connect research information through one structured environment.</p><div className="hero-actions"><a href="#workspace" className="button button-primary">Open research workspace <ArrowUpRight size={16} /></a><a href="#architecture" className="button button-quiet light">View architecture <ArrowUpRight size={16} /></a></div></div><Reveal className="product-art"><NetworkVisual compact /></Reveal></div></section><section className="product-workspace" id="workspace"><div className="container"><div className="product-heading"><div><SectionLabel>LIVE PRODUCT PREVIEW</SectionLabel><h2>Research, without the <em>scattered pieces.</em></h2></div><p>A calm, structured interface for turning information into a reusable team asset.</p></div><DashboardShell /></div></section><section className="section enterprise"><div className="container enterprise-grid"><div><SectionLabel>ENTERPRISE READY</SectionLabel><h2>Built for serious <em>research environments.</em></h2><p>Controlled access, structured knowledge, and evidence traceability form the foundation for teams working with high-value information.</p><div className="enterprise-list"><div><LockKeyhole size={19} /><span><b>Controlled access</b>Role-based access to research information.</span></div><div><Database size={19} /><span><b>Structured knowledge</b>Organized records, documents, references, and findings.</span></div><div><ShieldCheck size={19} /><span><b>Evidence traceability</b>Source-aware review and research activity history.</span></div></div><div className="enterprise-image"><img src="https://images.pexels.com/photos/37730211/pexels-photo-37730211.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" alt="Server rack in a secure data center" loading="lazy" /></div></div><div className="architecture-card" id="architecture"><small>TECHNICAL ARCHITECTURE</small>{['Research sources', 'Documents / references / records', 'Lorvane application', 'Laravel API layer', 'Search & retrieval', 'Intelligence layer', 'Knowledge discovery'].map((x, i) => <div key={x}><span>{String(i + 1).padStart(2, '0')}</span><b>{x}</b>{i < 6 && <ArrowUpRight size={15} />}</div>)}<div className="arch-end">Research workspace <ArrowUpRight size={15} /></div></div></div></section><CTA /><Footer /></>; }
export { Product };
