import { ArrowUpRight, BarChart3, FileText, Layers3, Network, Search, ShieldCheck } from 'lucide-react';
import { SectionLabel } from './SectionLabel';
import { Reveal } from './Reveal';

const capabilities = [
  { no: '01', icon: FileText, title: 'Research Records', text: 'You can create structured research records that capture the topic, background, findings, references, and important notes behind your work.', sub: 'We help you preserve the context of your research so that when you or your team return to it later, you don\'t have to start figuring everything out again.' },
  { no: '02', icon: Layers3, title: 'Knowledge Management', text: 'You already work with documents, references, notes, findings, and different sources of information. We give you one organized environment to bring them together.', sub: 'With Lorvane, you can structure your knowledge around projects, topics, and areas of research, making it easier for you and your team to find and reuse valuable information.' },
  { no: '03', icon: Search, title: 'Intelligent Discovery', text: 'When you\'re working through large amounts of research, finding the right information can take time. Lorvane helps you search across your stored knowledge and surface relevant content while keeping its source and context connected.', sub: '' },
  { no: '04', icon: ShieldCheck, title: 'Evidence Review', text: 'When you make a research decision, you need more than an interesting result. You need to understand the evidence behind it.', sub: 'Lorvane helps you connect your findings with supporting documents, references, and research context, giving you a clearer way to review what you\'ve discovered.' },
  { no: '05', icon: Network, title: 'Related Knowledge', text: 'Sometimes the most valuable insight isn\'t in the information you\'re looking at, it\'s in how that information connects to something you\'ve already explored.', sub: 'We help you connect related topics, records, documents, and findings so you can explore your research from different angles.' },
  { no: '06', icon: BarChart3, title: 'Research Activity', text: 'As your research grows, so does the need to understand what has already been explored.', sub: 'Lorvane helps you keep track of saved findings, research activity, reviewed materials, searches, and knowledge updates, giving you and your team a clearer view of the research journey.' },
];

function Capabilities() { return <section className="section capabilities" id="features"><div className="container"><div className="section-intro"><div><SectionLabel>WHAT LORVANE DOES</SectionLabel><h2>We built Lorvane to keep that journey connected.</h2></div><p>Lorvane, you can bring your research together, understand what you already know, discover what may be relevant next, and keep the evidence behind your work within reach.</p></div><div className="capability-grid">{capabilities.map(({ no, icon: Icon, title, text, sub }) => <Reveal className="capability-card" key={no}><div className="card-top"><span className="card-no">{no}</span><Icon size={24} /></div><h3>{title}</h3><p>{text}</p>{sub && <p className="card-sub">{sub}</p>}<ArrowUpRight className="card-arrow" size={18} /></Reveal>)}</div></div></section>; }
export { Capabilities };
